###
POST http://localhost:3000/api/v1/class/create
Content-Type: application/json

{
    "title": "Teste Aula 5",
    "start": "2022-07-20T00:37:07.036Z",
    "end": "2022-12-21T00:37:07.036Z",
    "id_professor": 1
}

###
GET http://localhost:3000/api/v1/class/get-all-from-teacher/1