###
POST http://localhost:3000/api/v1/discipline/create
Content-Type: application/json

{
    "nome": "Matematica",
    "professor_id": 1,
    "disciplina_id": 1
}

###
GET http://localhost:3000/api/v1/discipline/get-all