POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
    "email": "testeuser@gmail.com",
    "senha": "senhaDaniel"
}

### CREATE A USER 
POST http://localhost:3000/api/v1/users/create
Content-Type: application/json

{
    "usuario": "Daniel",
    "email": "daniel6@gmail.com",
    "senha": "senhaDaniel"
}