POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "danielfilipe2@gmail.com",
    "senha": "senhateste"
}

### CREATE A USER 
POST http://localhost:3000/api/users/create
Content-Type: application/json

{
    "nome": "Daniel",
    "email": "danielMaster@gmail.com",
    "senha": "senhaDaniel",
    "data": "2022-09-26T21:05:20.714Z"
}